### ISSUE TITLE
[BUG] Server hit timeout while starting / Couldn't pass ServerPreConnectEvent to impulse 0.3.2

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [Arson-Club/Impulse#84]
**Describe the bug**

Whenever I try to join, it seems the server successfully starts as verified by `impulse status survival`, but actually trying to join leaves my client on the "joining world" screen until it times out, after which the server spits the errors shown below.

**To Reproduce**
I'm not sure, please ask for any details that may lead to knowing. I just tried joining after completing the jar setup and this issue happened.

**Expected behavior**
I'm able to join and have fun

**Your config.yaml**
```yaml
instanceName: stussies
servers:
  - name: survival
    type: jar
    lifecycleSettings:
      timeouts:
        inactiveGracePeriod: 300
    jar:
      workingDirectory: 'C:\Users\******\Desktop\stussies minecraft server\stussies survival'
      jarFile: server.jar
      javaFlags:
        - -Xms4G
        - -Xmx4G
      flags:
        - --nogui
  - name: creative
    type: jar
    lifecycleSettings:
      timeouts:
        inactiveGracePeriod: 300
    jar:
      workingDirectory: 'C:\Users\******\Desktop\stussies minecraft server\stussies creative'
      jarFile: server.jar
      javaFlags:
        - -Xms4G
        - -Xmx4G
      flags:
        - --nogui
serverMaintenanceInterval: 300
messages:
  startupError: "<red>Server is starting, please try again in a moment...</red>\n\
    If this issue persists, please contact an administrator"
  reconcileRestartTitle: "<red>Server is Restarting...</red>"
  reconcileRestartMessage: "server restart imminent"
  autoStartDisabled: "<red>Autostart is disabled for this server</red>"
``` 

**Log Messages**

![Image](https://github.com/user-attachments/assets/5b1ffed3-fb81-428a-b342-2cbba8540255)

**Environment (please complete the following information):**
 - OS: Windows
 - JAR broker

**Versions:**
Which version of Impulse are you using? 0.3.2
Which version of Velocity are you using? 3.4.0-SNAPSHOT

**Additional context**
