### ISSUE TITLE
[BUG] Permission error & Plugin causes players to disconnect from backend forge server.

### ISSUE THREAD

**Issue by AMufInABox** [Arson-Club/Impulse#87]
**Describe the bug**
When attempting to connect to a forge backend server the connection times out.
Also is sending "[20:05:15 INFO] [impulse]: {"status":"error","error":"NOT_AUTHORIZED","error_data":"Permission Error: Missing permissions for this resource"} even with the correct api key."

**To Reproduce**
1. Attempt to join the server.
2. Attempts to transfer to backend server
3. Connection times out and spews error.

**Expected behavior**
To be sent to the backend server.

**Your config.yaml**
```yaml
instanceName: "velocity"
 
servers:
  - name: "coven"
    type: "crafty"
    lifecycleSettings:
      allowAutoStart: true
      allowAutoStop: false
      reconciliationBehavior: ON_STOP  
      shutdownBehavior: STOP          
      timeouts:
        startup: 120
        shutdown: 120
        reconciliationGracePeriod: 60
        inactiveGracePeriod: 6000
    crafty:
      serverID: "REDACTED_UUID"
      token: "REDACTED_TOKEN"
      craftyAddress: "https://localhost:8443"
 
  - name: "irl"
    type: "crafty"
    crafty:
      serverID: "REDACTED_UUID"
      token: "REDACTED_TOKEN"
      craftyAddress: "https://localhost:8443"
 
  - name: "bmc"
    type: "crafty"
    lifecycleSettings:
      allowAutoStart: true
      allowAutoStop: false
      reconciliationBehavior: ON_STOP  
      shutdownBehavior: STOP          
      timeouts:
        startup: 120
        shutdown: 120
        reconciliationGracePeriod: 60
        inactiveGracePeriod: 6000
    crafty:
      serverID: "REDACTED_UUID"
      token: "REDACTED_TOKEN"
      craftyAddress: "https://localhost:8443"
 
serverMaintenanceInterval: 60
 
messages:
  startupError: "<red>Server is starting, please try again in a moment...</red>\nIf this issue persists, please contact an administrator"
  reconcileRestartTitle: "<red>Server is Restarting...</red>"
  reconcileRestartMessage: "server restart imminent"
  autoStartDisabled: "<red>Autostart is disabled for this server</red>"
 
``` 

**Log Messages**
If applicable, attach any log messages from Impulse.
https://mclo.gs/KKFkSfw

**Environment (please complete the following information):**
 - OS: Linux (Debian)
 - I set up Impulse to be used with Crafty Controller. 

**Versions:**
Which version of Impulse are you using? v0.3.2
Which version of Velocity are you using? 3.4.0-SNAPSHOT

**Additional context**
I'm not sure if this is specifically caused by base plugin or by the crafty controller I set up as regardless when the config is loaded it spews out a not authorized error.
